version: "3.8"

services:
  app:
    stdin_open: true
    tty: true
    build:
      context: frontend/history-chat-bot
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  python_app:
    stdin_open: true
    tty: true
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - tts:/root/.local/share/tts
      - appstorage:/app

volumes:
  tts:
  appstorage:
